[package]
name = "Townesquare"
version = "0.4.0"

[addresses]
townesquare = "0xd9dfc03b5a835891c26a514104444c66f562ac07885e703cd412da656e41efd0"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

