[package]
name = 'townesquare_sc'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
townesquare_sc='deee649e72444ab1a7b7c5802251efd0030e48b1da75273c8fee0aa42d197fb4'
townesquare='deee649e72444ab1a7b7c5802251efd0030e48b1da75273c8fee0aa42d197fb4'