[package]
name = "Townesquare"
version = "0.4.0"

[addresses]
townesquare = "0x67e06bcc1e6c7dce9e2d2181eb675a967f7b93e19dfcdc57df1e06d863c4e421"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

