[package]
name = "Townesquare"
version = "0.4.0"

[addresses]
townesquare = "0x94adf62d48b39cdbf86dc7acef765ae70fc659508e4d8873b91c9566f01e07f0"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

