[package]
name = "Townesquare"
version = "0.2.1"

[addresses]
townesquare = "0x87421490ff3712fe34926bef989f92e9fc2a6900e98cf6c712ea97aaf67218c4"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

