[package]
name = "Townesquare"
version = "0.2.1"

[addresses]
townesquare = "0x6b7c8681599cd9f305df89719b99be9ae141f009610bc5f2baea8507be99ff81"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

