[package]
name = "Townesquare"
version = "0.2.0"

[addresses]
townesquare = "0x0743552991f364ab85d7c2ae7e9570bbc80c61d482c323c00b5b5ed4887fe60d"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

