// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::townesquare_state_created {

    use townesquare_sc::townesquare_state::{Self, TownesquareStateCreated};

    public fun is_emergency(townesquare_state_created: &TownesquareStateCreated): bool {
        townesquare_state::townesquare_state_created_is_emergency(townesquare_state_created)
    }

    public fun user_admin(townesquare_state_created: &TownesquareStateCreated): address {
        townesquare_state::townesquare_state_created_user_admin(townesquare_state_created)
    }

    public fun post_admin(townesquare_state_created: &TownesquareStateCreated): address {
        townesquare_state::townesquare_state_created_post_admin(townesquare_state_created)
    }

}
