// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::townesquare_sc_init {
    use townesquare_sc::genesis_account;
    use townesquare_sc::post;
    use townesquare_sc::townesquare_state;
    use townesquare_sc::user;

    public entry fun initialize(account: &signer) {
        genesis_account::initialize(account);
        post::initialize(account);
        user::initialize(account);
        townesquare_state::initialize(account);
    }

}
