// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::townesquare_state_updated {

    use townesquare_sc::townesquare_state::{Self, TownesquareStateUpdated};

    public fun is_emergency(townesquare_state_updated: &TownesquareStateUpdated): bool {
        townesquare_state::townesquare_state_updated_is_emergency(townesquare_state_updated)
    }

    public fun user_admin(townesquare_state_updated: &TownesquareStateUpdated): address {
        townesquare_state::townesquare_state_updated_user_admin(townesquare_state_updated)
    }

    public fun post_admin(townesquare_state_updated: &TownesquareStateUpdated): address {
        townesquare_state::townesquare_state_updated_post_admin(townesquare_state_updated)
    }

}
