// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::user_aggregate {
    use std::string::String;
    use townesquare_sc::user;
    use townesquare_sc::user_create_logic;
    use townesquare_sc::user_update_logic;

    public entry fun create(
        account: &signer,
        username: String,
        profile_image: String,
        bio: String,
    ) {
        let user_created = user_create_logic::verify(
            account,
            username,
            profile_image,
            bio,
        );
        let user = user_create_logic::mutate(
            account,
            &user_created,
        );
        user::add_user(user);
        user::emit_user_created(user_created);
    }

    public entry fun update(
        account: &signer,
        user_wallet: address,
        username: String,
        profile_image: String,
        bio: String,
    ) {
        let user = user::remove_user(user_wallet);
        let user_updated = user_update_logic::verify(
            account,
            username,
            profile_image,
            bio,
            &user,
        );
        let updated_user = user_update_logic::mutate(
            account,
            &user_updated,
            user,
        );
        user::update_version_and_add(updated_user);
        user::emit_user_updated(user_updated);
    }

}
