// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::user_created {

    use std::string::String;
    use townesquare_sc::user::{Self, UserCreated};

    public fun user_wallet(user_created: &UserCreated): address {
        user::user_created_user_wallet(user_created)
    }

    public fun username(user_created: &UserCreated): String {
        user::user_created_username(user_created)
    }

    public fun profile_image(user_created: &UserCreated): String {
        user::user_created_profile_image(user_created)
    }

    public fun bio(user_created: &UserCreated): String {
        user::user_created_bio(user_created)
    }

}
